
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Paquetes;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int Link = 37;
  public static final int PuntoComa = 28;
  public static final int IMPRIMIR = 34;
  public static final int Separador = 27;
  public static final int Variable = 35;
  public static final int InicioCuerpoDoc = 14;
  public static final int ENLACE = 36;
  public static final int DosPunto = 29;
  public static final int ParentesisCierre = 3;
  public static final int TituloEncabezado = 9;
  public static final int NumeroDecimal = 22;
  public static final int InicioImagen = 23;
  public static final int NEGRITA = 33;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int PRUEBA = 32;
  public static final int FinDocumento = 13;
  public static final int OperadorResta = 21;
  public static final int FinFila = 26;
  public static final int ParentesisAper = 2;
  public static final int InicioEncabezado = 8;
  public static final int InicioFila = 5;
  public static final int FinLista = 31;
  public static final int InicioColumna = 6;
  public static final int Correo = 25;
  public static final int FinTabla = 16;
  public static final int Identificador = 38;
  public static final int FinEncabezado = 10;
  public static final int InicioLista = 30;
  public static final int OperadorSuma = 20;
  public static final int InicioDocumento = 7;
  public static final int FinImagen = 24;
  public static final int OperadorMultiplicacion = 19;
  public static final int Numero = 12;
  public static final int BORDE = 4;
  public static final int InicioTabla = 11;
  public static final int Igual = 17;
  public static final int FinCuerpoDoc = 15;
  public static final int Comillas = 18;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ParentesisAper",
  "ParentesisCierre",
  "BORDE",
  "InicioFila",
  "InicioColumna",
  "InicioDocumento",
  "InicioEncabezado",
  "TituloEncabezado",
  "FinEncabezado",
  "InicioTabla",
  "Numero",
  "FinDocumento",
  "InicioCuerpoDoc",
  "FinCuerpoDoc",
  "FinTabla",
  "Igual",
  "Comillas",
  "OperadorMultiplicacion",
  "OperadorSuma",
  "OperadorResta",
  "NumeroDecimal",
  "InicioImagen",
  "FinImagen",
  "Correo",
  "FinFila",
  "Separador",
  "PuntoComa",
  "DosPunto",
  "InicioLista",
  "FinLista",
  "PRUEBA",
  "NEGRITA",
  "IMPRIMIR",
  "Variable",
  "ENLACE",
  "Link",
  "Identificador"
  };
}

